"use client";
/**
 * components/AISuggestionBox.tsx
 *
 * Displays an AI suggestion with mandatory labelling.
 *
 * Rules enforced by this component:
 * - Always shows the "AI SUGGESTION — NOT AUDITOR APPROVED" label.
 * - Always shows the disclaimer on expand.
 * - Never renders an approve/accept button — the caller handles that separately.
 * - Error states are shown clearly without exposing technical details.
 */

import { useState } from "react";

interface Props {
  suggestion: string | null;
  loading: boolean;
  error: string | null;
  onRequest: () => void;
  buttonLabel?: string;
  /** Optional: rendered after the suggestion text, e.g. a "Use as draft" button */
  action?: React.ReactNode;
}

export default function AISuggestionBox({
  suggestion,
  loading,
  error,
  onRequest,
  buttonLabel = "Get AI Suggestion",
  action,
}: Props) {
  const [disclaimerOpen, setDisclaimerOpen] = useState(false);

  return (
    <div className="space-y-2">
      {/* Trigger button */}
      {!suggestion && !loading && (
        <button
          type="button"
          onClick={onRequest}
          disabled={loading}
          className="flex items-center gap-1.5 text-xs px-3 py-1.5 rounded border border-amber-300 bg-amber-50 text-amber-800 hover:bg-amber-100 transition-colors font-medium disabled:opacity-50"
        >
          <span>✦</span> {buttonLabel}
        </button>
      )}

      {/* Loading */}
      {loading && (
        <div className="flex items-center gap-2 text-xs text-amber-700 bg-amber-50 border border-amber-200 rounded px-3 py-2">
          <span className="inline-block w-3 h-3 border-2 border-amber-500 border-t-transparent rounded-full animate-spin" />
          Generating AI suggestion…
        </div>
      )}

      {/* Error */}
      {error && !loading && (
        <div className="text-xs text-red-700 bg-red-50 border border-red-200 rounded px-3 py-2">
          ⚠ {error}
          <button
            type="button"
            onClick={onRequest}
            className="ml-2 underline hover:no-underline"
          >
            Retry
          </button>
        </div>
      )}

      {/* Suggestion */}
      {suggestion && !loading && (
        <div className="bg-amber-50 border border-amber-300 rounded-lg overflow-hidden">
          {/* Header */}
          <div className="flex items-center justify-between px-3 py-2 bg-amber-100 border-b border-amber-200">
            <div className="flex items-center gap-1.5">
              <span className="text-amber-600 font-bold text-xs">✦ AI SUGGESTION</span>
              <span className="text-amber-700 text-xs font-semibold">— NOT AUDITOR APPROVED</span>
            </div>
            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={() => setDisclaimerOpen((v) => !v)}
                className="text-xs text-amber-600 hover:underline"
              >
                {disclaimerOpen ? "Hide disclaimer" : "Disclaimer"}
              </button>
              <button
                type="button"
                onClick={onRequest}
                className="text-xs text-amber-600 hover:underline"
              >
                Regenerate
              </button>
            </div>
          </div>

          {/* Disclaimer (expandable) */}
          {disclaimerOpen && (
            <div className="px-3 py-2 text-xs text-amber-800 bg-amber-50 border-b border-amber-200 italic">
              This text was generated by AI (GPT-4o-mini) and has not been verified by a qualified engineer.
              It is for reference only. The auditor must independently assess all evidence and draw their own
              conclusions. AI suggestions have no effect on any approval, finding classification, or
              supplier qualification decision.
            </div>
          )}

          {/* Suggestion text */}
          <div className="px-3 py-3 text-sm text-slate-700 whitespace-pre-wrap">
            {suggestion}
          </div>

          {/* Optional action slot */}
          {action && (
            <div className="px-3 pb-3">
              {action}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
